// COLUMNS
export const COLUMNS = {
  DATE: ["DATE", "DATED"],
  CCY: ["CCY_ID"],
  FI: ["FI_ID", "FI_NAME"],
  COA: ["ME_COA"],
  FACILITY_TYPE: ["FACILITY_TYPE"],
  DECIMAL_EMPTY: [
    "AMOUNT",
    "AMOUNT BDT",
    "OUTSTANDING_AMOUNT",
    "DOWN_PAYMENT_AMOUNT",
    "INTEREST_SUSPENSE",
    "UNAPPLIED_INTEREST",
    "INTEREST_WAIVED",
    "AMOUNT_RESCHEDULED_EXIT",
  ],
  DECIMAL_NOT_EMPTY: ["EXCHANGE_RATE"],
  INTEGER_NOT_EMPTY: [
    "Open_Position_Limit",
    "FACILITY_TYPE",
    "APPLICATION_NO",
    "APPLICATION_APPROVED",
  ],
};
